image:
  repository: goran14/complete-devops-project
  tag: ff8dcdc
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80801

ingress:
  enabled: false

serviceAccount:
  enabled: false

autoscaling:
  enabled: false