---

name: Complete DevOps Project Pipeline

on:
  push:
    branches:
        - main

jobs:
    build_and_push:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v2
            
            - name: Set Short SHA
              run: |
                echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV
            
            - name: Build Docker image
              run: |
                docker build -t goran14/complete-devops-project:${{ env.SHORT_SHA }} .

            - name: Log in to DockerHub
              run: |
                echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            - name: Push DockerHub
              run: |
                docker push goran14/complete-devops-project:${{ env.SHORT_SHA }}

            - name: Configure Git Author
              run: |
                git config --local user.email "hello@goran1488.com"
                git config --local user.name "goran1488"    

            - name: Update Helm chart with new image tag
              run: |
                sed -i "s/tag:.*/tag: ${{ env.SHORT_SHA }}/" ./complete-devops-project-time-printer/values.yaml
                git add ./complete-devops-project-time-printer/values.yaml
                git commit -m "Update image tag to ${{ env.SHORT_SHA }}"
                git push